template_path: aurora.py

sceptre_user_data:
  project: {{ var.project }}
  prefix: {{ var.environment }}
  cluster_class: 'db.r3.xlarge'
  cluster_password: 'adminadmin'
  db_subnet_id_list:
    - !stack_output ap-northeast-1/vpc.yaml::DBSubnetList
  db_sg_list:
    - !stack_output ap-northeast-1/security-group.yaml::DBSGId
  deletion_protection: False