template_path: ec2.py

sceptre_user_data:
  project: {{ var.project }}
  prefix: {{ var.environment }}
  image_id: ami-0ce107ae7af2e92b5
  instance_type: t2.micro
  key_name: {{ var.key_name }}
  subnet_id_list:
    - !stack_output ap-northeast-1/vpc.yaml::PrivateSubnetList