template_path: load_barancer.py

sceptre_user_data: 
  project: {{ var.project }}
  prefix: {{ var.environment }}
  elb_log_bucket: !stack_output ap-northeast-1/s3.yaml::ElbLogBucket
  security_group_list:
    - !stack_output ap-northeast-1/security-group.yaml::WebSGId
  subnet_id_list:
    - !stack_output ap-northeast-1/vpc.yaml::WebSubnetList
  vpc_id: !stack_output ap-northeast-1/vpc.yaml::VpcId