template_path: route_table.py

sceptre_user_data:
  project: {{ var.project }}
  prefix: {{ var.environment }}
  vpc_id: !stack_output ap-northeast-1/vpc.yaml::VpcId
  igw_id: !stack_output ap-northeast-1/vpc.yaml::IgwId
  web_subnet_list: !stack_output ap-northeast-1/vpc.yaml::WebSubnetList
  private_subnet_list: !stack_output ap-northeast-1/vpc.yaml::PrivateSubnetList
  db_subnet_list: !stack_output ap-northeast-1/vpc.yaml::DBSubnetList
