template_path: vpc.py

sceptre_user_data:
  project: {{ var.project}}
  prefix: {{ var.environment}}
  vpc_cidr_block: '10.0.0.0/16'
  web_subnet_addrs:
    - '10.0.0.0/24'
    - '10.0.1.0/24'
  private_subnet_addrs:
    - '10.0.2.0/24'
    - '10.0.3.0/24'
  db_subnet_addrs:
    - '10.0.4.0/24'
    - '10.0.5.0/24'
